import type { ShipDefinition, WeaponDefinition, WeaponKind } from './types';

const degrees = (value: number): number => (value * Math.PI) / 180;

export const WEAPONS: Readonly<Record<WeaponKind, WeaponDefinition>> = {
  broadside: {
    kind: 'broadside',
    name: 'Mass Driver Broadside',
    arc: 'broadside',
    range: 470,
    halfAngle: degrees(56),
    apCost: 1,
    energyCost: 8,
    accuracy: 86,
    minDamage: 38,
    maxDamage: 48,
    shieldMultiplier: 1,
  },
  lance: {
    kind: 'lance',
    name: 'Rift Lance',
    arc: 'front',
    range: 640,
    halfAngle: degrees(52),
    apCost: 1,
    energyCost: 18,
    accuracy: 93,
    minDamage: 44,
    maxDamage: 56,
    shieldMultiplier: 1.35,
  },
  torpedo: {
    kind: 'torpedo',
    name: 'Void Torpedo',
    arc: 'front',
    range: 680,
    halfAngle: degrees(60),
    apCost: 1,
    energyCost: 10,
    accuracy: 100,
    minDamage: 54,
    maxDamage: 66,
    shieldMultiplier: 1,
  },
};

export const SHIPS: readonly ShipDefinition[] = [
  {
    id: 'p-cruiser',
    team: 'player',
    name: "Sovereign's Fury",
    class: 'cruiser',
    maxHull: 112,
    maxShield: 68,
    shieldRegen: 0,
    armor: 0.1,
    maxEnergy: 80,
    energyRegen: 16,
    maxAp: 1,
    moveRange: 255,
    radius: 48,
    weapons: ['broadside', 'lance', 'torpedo'],
    startPosition: { x: 350, y: 1_160 },
    startFacing: -Math.PI / 2,
  },
  {
    id: 'p-frigate',
    team: 'player',
    name: 'Aster Vale',
    class: 'frigate',
    maxHull: 72,
    maxShield: 38,
    shieldRegen: 0,
    armor: 0.05,
    maxEnergy: 68,
    energyRegen: 18,
    maxAp: 1,
    moveRange: 315,
    radius: 34,
    weapons: ['lance', 'torpedo'],
    startPosition: { x: 675, y: 1_250 },
    startFacing: -Math.PI / 2,
  },
  {
    id: 'e-cruiser',
    team: 'enemy',
    name: 'Ashen Crown',
    class: 'cruiser',
    maxHull: 102,
    maxShield: 54,
    shieldRegen: 0,
    armor: 0.08,
    maxEnergy: 74,
    energyRegen: 15,
    maxAp: 1,
    moveRange: 235,
    radius: 46,
    weapons: ['broadside', 'lance'],
    startPosition: { x: 380, y: 330 },
    startFacing: Math.PI / 2,
  },
  {
    id: 'e-destroyer',
    team: 'enemy',
    name: 'Red Wake',
    class: 'destroyer',
    maxHull: 64,
    maxShield: 32,
    shieldRegen: 0,
    armor: 0.04,
    maxEnergy: 65,
    energyRegen: 17,
    maxAp: 1,
    moveRange: 285,
    radius: 38,
    weapons: ['lance', 'torpedo'],
    startPosition: { x: 705, y: 410 },
    startFacing: Math.PI / 2,
  },
];
